// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "mbapp-20180923132022--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://mbapp-20180923132022--hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:7753fb15-0c99-4a5a-baa2-ac84dbf706cb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ot86UPEUI",
    "aws_user_pools_web_client_id": "12q15fsop8pqqnfijut8v7ucdf",
    "aws_mobile_analytics_app_id": "2b34c4c3cd8a45d4b02337d3a8c98766",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_user_files_s3_bucket": "mbappf0e8f67547ee4b7eb97100b062bba1f2",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamombapprestapi",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://ximcm6el55gxpcha7mvwshawna.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "mbapprest",
            "endpoint": "https://trmulf0cv8.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
